server:
  port: 0
  servlet:
    context-path: /notification/api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: 123
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka