spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mabr
    username: postgres
    password: 123
    hikari:
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./data/index
  liquibase:
    change-log: db/changelog/changelog.xml
springdoc:
  swagger-ui:
    operations-sorter: method
jwt:
  secret: 5367566B59703EQWRTRGFBP92F423F4528482B4D6251655468576D5A71383482

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka