global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'file_storage_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['file-storage-service:8080']
        labels:
          application: 'File storage service Application'
  - job_name: 'messenger_service'
    metrics_path: '/messenger/api/actuator/prometheus'
    static_configs:
      - targets: ['messenger-service:8080']
        labels:
          application: 'Messenger service Application'
  - job_name: 'authentication_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication-service:8080']
        labels:
          application: 'Authentication service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'