spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: file-storage-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
server:
  port: 0
  servlet:
    context-path: /file-storage/api/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    io:
      minio: DEBUG
minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  put-object-part-size: 5242880