server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5431/user_service
    username: postgres
    password: 123

eureka:
  client:
    service-url:
      defaultZone : http://eureka:password@discovery-server:8761/eureka
