server:
  port: 0
  servlet:
    context-path: /authentication/api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123
  application:
    name: authentication-service

jwt:
  secret: 5367566B59703EQWRTRGFBP92F423F4528482B4D6251655468576D5A71383482

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka