CREATE SCHEMA security;
CREATE SCHEMA data;
CREATE SCHEMA post;

CREATE TABLE data.city
(
    id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_en text NOT NULL,
    name_ru text NOT NULL
);

CREATE TABLE data.currency
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL
);

CREATE TABLE data.label
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL
);

INSERT INTO data.city (id, name_en, name_ru)
VALUES (0, '', 'Не указано'),
       (4, 'Belarus', 'Беларусь'),
       (2, 'Russia', 'Россия'),
       (1, 'Kazakhstan', 'Казахстан'),
       (3, 'Ukraine', 'Украина');

INSERT INTO data.currency (id, name)
VALUES (0, 'Не указано'),
       (1, 'KZT'),
       (2, 'RUB'),
       (3, 'EUR'),
       (4, 'USD');

INSERT INTO data.label (id, name)
VALUES (1, 'IT'),
       (2, 'Наука'),
       (3, 'Экономика');
