server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/messenger_service
    username: postgres
    password: 123
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone : http://eureka:password@discovery-server:8761/eureka
