spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: messenger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 0
  servlet:
    context-path: /messenger/api/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    io:
      minio: DEBUG