spring:
  application:
    name: messenger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mabr
    username: postgres
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082