spring:
  application:
    name: messenger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082
  servlet:
    context-path: /messenger/api/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka