spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: messenger-service
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 0
  servlet:
    context-path: /messenger/api/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    io:
      minio: DEBUG
management:
  endpoints:
    web:
      exposure:
        include : health, metrics, prometheus
  endpoint:
      health:
        show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      message:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based